return {
	Normal = { fg = c.vscFront, bg = c.vscBack },
	ColorColumn = { fg = c.vscNone, bg = c.vscCursorDarkDark },
	Cursor = { fg = c.vscCursorDark, bg = c.vscCursorLight },
	CursorLine = { bg = c.vscCursorDarkDark },
	CursorColumn = { fg = c.vscNone, bg = c.vscCursorDarkDark },
	Directory = { fg = c.vscBlue, bg = c.vscBack },
	DiffAdd = { fg = c.vscNone, bg = c.vscDiffGreenLight },
	DiffChange = { fg = c.vscNone, bg = c.vscDiffRedDark },
	DiffDelete = { fg = c.vscNone, bg = c.vscDiffRedLight },
	DiffText = { fg = c.vscNone, bg = c.vscDiffRedLight },
	EndOfBuffer = { fg = c.vscBack, bg = c.vscNone },
	ErrorMsg = { fg = c.vscRed, bg = c.vscBack },
	VertSplit = { fg = c.vscSplitDark, bg = c.vscBack },
	Folded = { fg = c.vscNone, bg = c.vscFoldBackground },
	FoldColumn = { fg = c.vscLineNumber, bg = c.vscBack },
	SignColumn = { fg = c.vscNone, bg = c.vscBack },
	IncSearch = { fg = c.vscNone, bg = c.vscSearchCurrent },
	LineNr = { fg = c.vscLineNumber, bg = c.vscBack },
	CursorLineNr = { fg = c.vscPopupFront, bg = c.vscBack },
	MatchParen = { fg = c.vscNone, bg = c.vscCursorDark },
	ModeMsg = { fg = c.vscFront, bg = c.vscLeftDark },
	MoreMsg = { fg = c.vscFront, bg = c.vscLeftDark },
	NonText = { fg = c.vscLineNumber, bg = c.vscNone },
	Pmenu = { fg = c.vscPopupFront, bg = c.vscPopupBack },
	PmenuSel = { fg = c.vscPopupFront, bg = c.vscPopupHighlightBlue },
	PmenuSbar = { fg = c.vscNone, bg = c.vscPopupHighlightGray },
	PmenuThumb = { fg = c.vscNone, bg = c.vscPopupFront },
	Question = { fg = c.vscBlue, bg = c.vscBack },
	Search = { fg = c.vscNone, bg = c.vscSearch },
	SpecialKey = { fg = c.vscBlue, bg = c.vscNone },
	StatusLine = { fg = c.vscFront, bg = c.vscLeftMid },
	StatusLineNC = { fg = c.vscFront, bg = c.vscBack },
	TabLine = { fg = c.vscFront, bg = c.vscTabOther },
	TabLineFill = { fg = c.vscFront, bg = c.vscTabOutside },
	TabLineSel = { fg = c.vscFront, bg = c.vscTabCurrent },
	Title = { fg = c.vscNone, bg = c.vscNone, bold = true },
	Visual = { fg = c.vscNone, bg = c.vscSelection },
	VisualNOS = { fg = c.vscNone, bg = c.vscSelection },
	WarningMsg = { fg = c.vscRed, bg = c.vscBack, bold = true },
	WildMenu = { fg = c.vscNone, bg = c.vscSelection },
	Comment = { fg = c.vscGreen, bg = c.vscNone, italic = false },
	Constant = { fg = c.vscBlue, bg = c.vscNone },
	String = { fg = c.vscOrange, bg = c.vscNone },
	Character = { fg = c.vscOrange, bg = c.vscNone },
	Number = { fg = c.vscLightGreen, bg = c.vscNone },
	Boolean = { fg = c.vscBlue, bg = c.vscNone },
	Float = { fg = c.vscLightGreen, bg = c.vscNone },
	Identifier = { fg = c.vscLightBlue, bg = c.vscNone },
	Function = { fg = c.vscYellow, bg = c.vscNone },
	Statement = { fg = c.vscPink, bg = c.vscNone },
	Conditional = { fg = c.vscPink, bg = c.vscNone },
	Repeat = { fg = c.vscPink, bg = c.vscNone },
	Label = { fg = c.vscPink, bg = c.vscNone },
	Operator = { fg = c.vscFront, bg = c.vscNone },
	Keyword = { fg = c.vscPink, bg = c.vscNone },
	Exception = { fg = c.vscPink, bg = c.vscNone },
	PreProc = { fg = c.vscPink, bg = c.vscNone },
	Include = { fg = c.vscPink, bg = c.vscNone },
	Define = { fg = c.vscPink, bg = c.vscNone },
	Macro = { fg = c.vscPink, bg = c.vscNone },
	Type = { fg = c.vscBlue, bg = c.vscNone },
	StorageClass = { fg = c.vscBlue, bg = c.vscNone },
	Structure = { fg = c.vscBlueGreen, bg = c.vscNone },
	Typedef = { fg = c.vscBlue, bg = c.vscNone },
	Special = { fg = c.vscYellowOrange, bg = c.vscNone },
	SpecialChar = { fg = c.vscFront, bg = c.vscNone },
	Tag = { fg = c.vscFront, bg = c.vscNone },
	Delimiter = { fg = c.vscFront, bg = c.vscNone },
	SpecialComment = { fg = c.vscGreen, bg = c.vscNone },
	Debug = { fg = c.vscFront, bg = c.vscNone },
	Underlined = { fg = c.vscNone, bg = c.vscNone, underline = true },
	Conceal = { fg = c.vscFront, bg = c.vscBack },
	Ignore = { fg = c.vscFront, bg = c.vscNone },
	Error = { fg = c.vscRed, bg = c.vscBack, undercurl = true, sp = c.vscRed },
	Todo = { fg = c.vscYellowOrange, bg = c.vscBack, bold = true },
	SpellBad = { fg = c.vscRed, bg = c.vscBack, undercurl = true, sp = c.vscRed },
	SpellCap = { fg = c.vscRed, bg = c.vscBack, undercurl = true, sp = c.vscRed },
	SpellRare = { fg = c.vscRed, bg = c.vscBack, undercurl = true, sp = c.vscRed },
	SpellLocal = { fg = c.vscRed, bg = c.vscBack, undercurl = true, sp = c.vscRed },
	Whitespace = { fg = c.vscLineNumber },
}
